### ISSUE TITLE
Set asset label value by default

### ISSUE THREAD

**Issue by toast-gear** [shogo82148/actions-upload-release-asset#265]
I'm not even sure if that is right tbh however I need to be able to define a predictable download URL as I am uploading chart .tgz files and using GitHub as a Helm feed. A release asset upload URL looks like this:

`"https://uploads.github.com/repos/octocat/Hello-World/releases/1/assets{?name,label}",`

I need the label to be a predictable value as it needs to be set in my Helm index file for my Helm feed. Could this get set by default as the file name without the file extension? I'd rather not have to subsequently go and query the API to find the uploaded assets ID

As it stands you get:

`"/${owner}/${repo}/releases/download/${random_int_id}/${asset_file_name}"`

If we don't want to set it by default then having a new input to set it would be good:

```yaml
with:
  upload_url: ${{ github.event.release.upload_url }}
  asset_path: assets.txt
  set_asset_label: true
```
